### ISSUE TITLE
Release Improvements

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#1664]
The aim of this issue is to track the changes required to simplify the release process and make @cdrage's life easier, or allow others to perform releases.

I think the process should end up being three steps only, via a script or possibly the GitHub UI. 

1. Create PR with updated change log for the new version.
2. Merge PR.
3. Create tag for the new version. 

The rest of the process should be handled automatically, triggered by creating the tag. 

----
 
 - [x] Automatically add the Windows installer to GitHub release (#328)
 - [x] Update the release information using travis from the change log (#328)
 - [x] Include README in the package long_description (#1665)
 - [x] Automatically deploy the `streamlink` package to PyPI (#1701)
 - [x] Automatically add the sdist package GitHub release (#1701)
 - [x] Deploy a wheel to PyPI (#1701)
 - [ ] stable/dev versions of the docs (#1684 WIP)
 - [x] Make the change log consistently markdown, and include it in the docs using `recommonmark` (#1667)
 - [x] Only include installation/open collective in GitHub release info (#1667) 

1. We can include the README.md file in the package metadata as long_description to improve the appearance of the `streamlink` package on PyPI. See https://pypi.org/project/streamlink/0.12.1/ to see how it looks right now.

1. We _could_ deploy the `streamlink` package to PyPI automatically when creating a release tag, this would streamline the release process and remove some of the manual work and possibility for mistakes.

1. We _could_ add the `sdist` package to the GitHub release automatically with the release tag, as we do with the Windows installer. 

1. We _could_ also deploy a wheel to PyPI either automatically or manually, depending on what we do with the others. This might speed up installations in some cases, and is the preferred binary distribution method - but each platform variant might need its own wheel.

1. Separate the docs in to 2 streams (dev and stable), where stable is the default page. A link to the dev version will also need to be added a long with a note stating that is it the development/nightly version. Possibly we could deploy the dev docs at the same time as the nightlies are built, and deploy the stable version on release tag. 

1. The change log is currently a mix of reStructuredText and Markdown, it should be Markdown only. It should be able to be included in the docs by using `recommonmark` in Sphinx to render the Markdown. 

1. The installation instructions and open collective info don't need to be included for every single version in the release log, they are useful in the GitHub releases though. The script that updates the GitHub releases can be modified to include this template, then it doesn't need to be included in the change log. 

As always, it would be nice to have some feedback from the rest of you! I'm sure there are some other things we can improve 😄

**Comment by cdrage** [comment]
I've been having troubles staying on-time some days due to work conflicts, but if anyone else wants to do a release, feel free to! :+1: The release script is pretty straight-forward. 

I'll still do a release however every 2-3 weeks if there's any huge-changes that need to be merged in / released!

**Comment by bastimeyer** [comment]
> include the README.md file

:+1: 

> deploy the streamlink package to PyPI automatically

The less human interaction during the build and deploy process, the better. The only requirement for a release should be authorization, which can be accomplished with signed tags. If this is too much, just keep using regular tags and everyone with push rights can then trigger a new release. I'm not entirely sure, but I think a streamlink-bot would violate the ToS of Github.

> separate the docs in to 2 streams

I'm not sure how this works, but if it's not too much work, this gets a big :+1: from my side

> change log markdown

I'll review #1667 tomorrow

> open collective only on github releases page

sounds reasonable

**Comment by beardypig** [comment]
@bastimeyer I have started separating the docs, @back-to provided some suggestions in using `doctr`. I have had a stab at updating the docs to add version switching and a warning that the user is reading the docs for the unstable version - it would be good if you could check it out and maybe suggestion some css + text improvements :)

**Comment by bastimeyer** [comment]
According to https://github.com/beardypig/streamlink/commit/8f398c31fee0c2a5fb58b15772af38070c8e9e31#diff-354f30a63fb0907d4ad57269548329e3R41, it'll deploy the built docs in different subdirs, `/latest` and `/`, is that right? The `scripts/{make,push}docs.sh` scripts can be deleted then, I guess...

Regarding the changes of the doc templates/stylesheets, I don't know which vars are available in the modified templates, but this seems to work fine. Having the actual versions in the links instead of "stable" and "latest" would be a bit nicer, though. The issues I've noticed were a typo in one of the CSS selectors which changes the layout of the notification header a bit and another layout issue regarding the icon of the title of the box in the bottom right corner. I'd personally move the box from the bottom right corner and make it so that it can be selected at the top of the main menu, so that it's clearer that you can switch between different versions.

Let me try to make some further modiciations today or tomorrow. I'll let you know.

**Comment by beardypig** [comment]
Thanks @bastimeyer. Yeah, he dev version should go to latest and the stable to the root directory, and those scripts can be removed :)

There is a `release` and `version` variable I think, but because each doc deployment is separate the stable version doesn’t know about the version of the unstable one (unstable can infer the stable version though), so better to keep it neutral, I think.

**Comment by back-to** [comment]
> PyPI / wheel

**easy** https://docs.travis-ci.com/user/deployment/pypi/

---

> Automatically add the sdist package GitHub release

**complicated**

because the file is signed and it's maybe used for other packages

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/streamlink#n18

---

> Having the actual versions in the links instead of "stable" and "latest" would be a bit nicer, though. 

**easy** you can push docs on a tag to ... `/0.12.1` `/0.13.0` `/0.14.0` so it's archived there,
it's just one more line in the code.

I don't know if github can be used for a redirect from `/` to `/stable` ,
but just `/` for backwards compatibility is also ok.

so it will be

```
/ or /stable --> stable
/latest --> git version
/0.12.1 --> archive of tag
/0.13.0 --> archive of tag
/0.14.0 --> archive of tag
```

**Comment by beardypig** [comment]
Good suggestion @back-to, but how do you update the list of versions in the docs?

**Comment by back-to** [comment]
that would be probably to difficult,
I thought more of a **_hidden archive_** if you want to review an older version

sure an updated list would be great, but that's not really worth the effort.

**Comment by beardypig** [comment]
I think that's what @bastimeyer was asking about. I have updated the travis file to build each tag to its own directory... maybe there is a way to include a list of the other versions - but I think it's not worth it, like you said :)

**Comment by bastimeyer** [comment]
Since the docs get built independently, there are two options if we want to show the version strings instead of "stable" and "latest":
- rebuild the docs on every release / commit (unfeasible if all releases get listed, not so much if it's just the latest release and the current git HEAD)
- write the release and latest version data into a json file and make the docs load it dynamically (doesn't work if js is disabled... web crawlers, etc)

**Comment by beardypig** [comment]
With regards to signing the package on travis, we could generate a new key for `Streamlink <streamlink@protonmail.com>` and use that to sign the tar balls. We'd also have to make sure we have a revocation certificate stored safely so that we could revoke it in the case of a travis breach and issue a new one. We should publish the key id on the release page too. 
Provided there is no breach in travis, this should verify that the tarball that you download is the same one that was built on travis. Or, we just don't bother signing them...

**Comment by back-to** [comment]
looks like everything from this list is merged

closing
