### ISSUE TITLE
The road towards 2.0.0

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3235]
Let's prepare a checklist for the py2 removal and the 2.0.0 release. As said, we should also clean up all the deprecated stuff and remove the remaining cruft after bumping the required Python version, and include that in the 2.0.0 release.

Since nobody wants to do this on a separate branch and deal with conflicts later on, we'll have to publish another release first with the current changes and then get the changes merged on the master branch one by one.

I really want to push the progress on this now, so that it's finally over.

----

- [x] **Publish the last minor or patch release on 1.x**
  Just so that the current plugin fixes and other unrelated changes are not stuck on the master branch until work on 2.0.0 has been completed.
  https://github.com/streamlink/streamlink/releases/tag/1.7.0

- [x] **Python version requirements**
  - [x] Remove Python 2 support
    #3232 
  - [x] Set min Python version to 3.6
    #3269
  - [x] Remove py2 stuff from compatibility modules
    #3270
  - [ ] Remove remaining compatibility code from various modules, eg. `python-requests` related stuff
    Optional, `streamlink.packages` can be ignored.
  - [x] Upgrade to modern py3 syntax
    Optional, can mostly be automated via [`pyupgrade`](https://github.com/asottile/pyupgrade).
    `streamlink.packages` can be ignored.
    - [x] u-string removal
      #3311
    - [ ] ~~f-strings / implicit str.format syntax~~
    - [x] `yield from`
      #3280, #3368
    - [x] super calls
      #3307
    - [x] implicit class inheritance
      #3368
    - [x] dict comprehensions and set literals
      #3368
    - [x] OSError
      #3368

- [x] **Changes which otherwise require a major version bump**
  - [x] Remove all suppressed argparse parameters, including plugin parameters
    #3277
  - [x] Replace various `mux-subtitles` plugin parameters with a global one
    #3324
  - [x] Fix old log calls
    #3274
  - [x] Remove deprecated logger classes and compat classes
    #3273
  - [x] Remove `LIVESTREAMER_VERSION` constant from streamlink_cli
    #3275
  - [x] Remove compat parameters from `HLSStream.parse_variant_playlist`
    #3347
  - [x] Remove compat key names from `Session.{g,s}et_option`
    #3349
  - [x] Remove `plugin.api.support_plugin`, as it's unused and unnecessary
    #3398

- [x] **Changes which were blocked by py2, but are optional for 2.0.0**
  - [x] Transition from `imp` to `importlib`
    #3366

**Comment by back-to** [comment]
> Remove py2 stuff from compatibility modules

[Pull Requests](https://github.com/streamlink/streamlink/pulls) should be near **zero** before you break major stuff,
which would make more merge conflicts.

> Upgrade to modern py3 syntax
Optional, can mostly be automated 

could be automated, but it should be readable at the end. Not just one big patch file.

**Comment by bastimeyer** [comment]
The compat removal shouldn't break anything and unless I've missed something, all currently open PRs with the exception of those which should be merged before the next release don't import from the compat modules, so there won't be any conflicts to solve.

Regarding the next release, I'd suggest having this in the next couple of days or at least this week, as there are changes regarding Twitch's embedded ads which should be released as soon as possible.

The compat removal is already prepared and I will take a look at the deprecated logging stuff until then, so that it can be opened as a PR right away and doesn't block the 2.0.0 release. The other deprecation stuff is minor and rather simple. And as said, the other changes are all optional. If one wants to do this, just like back-to said, this needs to be done in logical chunks, which means that if `pyupgrade` gets used for this job, it needs to be modified step by step, as it doesn't have CLI params for selecting the code changes by type.

**Comment by beardypig** [comment]
Just a note for the future;

There are a lot of instances where `yield from` could be used, for example in cases like this
```python
  for s in HLSStream.parse_variant_playlist(self.session, url).items():
    yield s
```

**Comment by bastimeyer** [comment]
@beardypig I'd like to remove the compat key names from `Session`:
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink/session.py#L249-L257
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink/session.py#L307-L313

but I don't know what to do with the compat argparse arguments:
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink_cli/argparser.py#L935
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink_cli/argparser.py#L944
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink_cli/argparser.py#L1032
- https://github.com/streamlink/streamlink/blob/cc6d777758c38697eb6a53c3ee5e8d411bf5eb70/src/streamlink_cli/argparser.py#L1042

Should the old arguments be removed as well?

Btw, `-e` and `-c` should be re-ordered and defined first, because it's looking weird in the docs. Otherwise, the docs' `ext_argparse` needs to sort all args automatically.

**Comment by beardypig** [comment]
@bastimeyer good question. Removing the key mapping in `Session` can be done for sure. 

I suggest that the `subprocess-errorlog`/`subprocess-errorlog-path` options should be combined in to a single `File-like` object (or `None`), that way the UI can do whatever it wants to handle the output log, then use that pattern for any other output files generated (eg. `ffmpeg-verbose`). We might want to adjust the names too, so they are more consistent.

**Comment by bastimeyer** [comment]
I'd say once the new docs theme has been merged (#3335), we should write up the changelog and see what's still missing for the `2.0.0` release. The checklist I've written and constantly updated in the OP is pretty much done.
