### ISSUE TITLE
3.0.0 checklist

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4145]
Let's prepare a checklist for the next release. Since there's a breaking change on the master branch (#4068), the next release will require a major version bump. This raises the question if we should remove some of the previously deprecated stuff now or postpone it, and if there are more breaking changes that should be included now.

### Breaking changes

- [x] #4091
  Changing `Session.resolve_url` to return plugin classes instead of plugin class instances would fix that bug, but would be a breaking change. This should ideally be done now.
- [x] #4040
  All plugins which previously imported the old protocol implementations have already been changed / fixed / removed. Only ustreamtv is left with a custom protocol that requires `streamlink.packages.flashmedia`.
  Protocol plugins could be removed, but since flashmedia can't be removed yet due to ustreamtv, it doesn't make too much sense dropping them now while keeping the flashmedia package.
  - [x] RTMPStream
    Removing it now would enable the removal of rtmpdump.
  - [x] HDS / AkamaiHD
    These two are the most irrelevant protocols today.
  - [x] `streamlink.packages.flashmedia`
    I've been working on a ustreamtv re-implementation, but this requires a new generic websocket session implementation first if I want to do it right, and this still needs more time to finalize. Other plugins like twitcasting and nicolive which require websocket stuff will benefit from this as well, as there's currently a lot of duplicate boilerplate code. I've already finished rewriting the twitcasting plugin and am in the final stages of the nicolive plugin and both are using the new websocket session. ustreamtv will come afterwards. I need to do it this way so I can see if the design and implementation is good enough, because there were two different websocket-client APIs in use by those plugins prior to that.

### Dependencies

- [x] #4170 
  May be worth including this in 3.0.0 and cleaning up the optional dependencies

### Currently deprecated stuff that could be removed

We don't have any deadlines for the deprecated stuff, so let's take a quick look.
https://streamlink.github.io/latest/deprecations.html

- [ ] ~~Config and cache dirs/paths, and plugin sideloading paths~~
  Could be done because postponing the removal until another major release could be a bit overwhelming for the user if there are more breaking changes on that release. However, it still feels a bit early, so I would say that we should keep it for now.
- [ ] ~~`Plugin.can_handle_url()` and `Plugin.priority()`~~
  Should only be done when there's a new plugin resolver
- [ ] ~~Stream-type related CLI arguments~~
  Way too early as they only have been deprecated in the last release
- [x] Other suppressed CLI arguments
  - [x] `--rtmpdump`
    Deprecated alias for `--rtmp-rtmpdump`. Should be removed with RTMPStream.
  - [ ] ~~`--hls-stream-segment-data`~~
    CLI argument got restored (#4126).

### Open issues that should be resolved first

- [x] #4126
  As I mentioned there, this may be a bug in requests/urllib3. Reverting `stream=True` could be an option, but that would require adding back `--hls-stream-segment-data`.
