### ISSUE TITLE
Refactor segmented streams and use a common BaseSegment

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#5498]
While talking about the extensibility and lack of full typing information of the segmented stream implementations in the past, I already mentioned that the base implementations of segmented streams, as well as HLS and DASH are in need of a huge code refactoring.

Now with my attempt at turning the `--hls-duration` and `--hls-start-offset` options into the generic `--stream-segmented-duration` and `--stream-segmented-start-offset` options, it became clear to me that it didn't make sense finishing that work with the current code.

See #5450 and https://github.com/streamlink/streamlink/pull/5493#issuecomment-1677680058.

----

The issue I'm intending to solve, ignoring all other flaws for now (there are a lot), is making both HLS, DASH and other subclasses of the segmented stream base classes share more common logic in regards to how segments are handled. I also want to fix the lack of typing information, so working with and understanding the segmented stream implementations is much easier.

Currently, each segmented stream implementation does its own thing with its segments, so implementing common logic for calculating a max stream duration or a stream start offset for example is impossible without writing lots of duplicate code with only small variations. This is also the reason why adding proper typing information can't be done. Writing logic for the same thing in each segmented stream type just doesn't make sense.

----

The big outlier here is HLS, where segments are wrapped in a `Sequence` named tuple. This is due to historic reasons when the segmented streams were initially implemented. Segments of each stream type were defined as named tuples which don't support subclassing or changing values after instantiation, so in order for the HLS stream's M3U8 parser to work properly, the generated segments needed to be wrapped, so a sequence number could be added after parsing the playlist as a whole (`EXT-X-MEDIA-SEQUENCE`).

While refactoring/rewriting the DASH implementation earlier this year, I already replaced its segments with ones that are based on the stdlib's `dataclasses`. Those fix all the issues that come with named tuples, but `dataclasses` come at the cost of a slight performance hit compared to named tuples. That is negligible though and is not important. It doesn't matter for Streamlink.

With dataclass segments, a `BaseSegment` type can be created which HLS, DASH and other can inherit from. The base `SegmentedStream{Worker,Writer,Reader}` classes can then properly handle the `BaseSegment` objects, and common base logic for max stream durations and start offsets could be added. Then fixing the lack of typing information would be much easier, too.

----

While this would affect huge parts of the base segmented stream stuff, as well as HLS and DASH, I don't think that there are any breaking changes involved. Public interfaces have never been declared on the stream implementations other than the main classes' constructors and classmethods like `HLSStream.parse_variant_stream()` and `DASHStream.parse_manifest()`. Those won't be touched.

Anything internal, like certain attribute names and methods, regardless whether they have docstrings attached or their names not starting with an underscore character are not part of the public interface, even if some plugins create stream subclasses and override them.

That's why I won't feel bad if any changes being made will break 3rd party plugins.

----

My initial improvised plan is this:

- [x] Refactor `stream.segmented`
  - [x] Change how the segments get put into and read from the queue (#5504)
  - [x] Add typing, with generic classes which define the segment type and segment data return type (#5507)
- [x] Refactor `stream.hls` and `stream.hls_playlist` (#5526)
  - Turn `Segment` and `Playlist` from named tuples into dataclasses
  - Move segment number generation from `HLSStreamWorker` to the `M3U8` parser
  - Replace the `Sequence` named tuple wrapper in HLS streams with a flat `Segment` dataclass type
  - Rename internal `HLSStream{Writer,Worker}` attributes and methods (including args+keywords)
  - Refactor M3U8 playlist loading
  - Fix / add more typing annotations
- [x] Refactor `stream.dash` and `stream.dash_manifest`
  - Fix/update all the worker/writer/reader parts
  - Fix / add more typing
- [x] Refactor / fix plugins
  - [x] `plugins.twitch` (#5526)
  - [x] `plugins.ustreamtv`
  - [x] other plugins with HLS stream subclasses (#5526)
- [x] Switch to sub-packages for `stream.segmented`, `stream.hls` and `stream.dash`
- [x] Rename HLS `Segment` to `HLSSegment` and DASH `Segment` to `DASHSegment`
- [x] Add base `Segment` with common attributes (`uri`, `num`, `duration`)
  - [x] Make `{HLS,DASH,UStreamTV}Segment` inherit from it and bind `Segment` to `TSegment_co`
- [ ] Add common logic for segmented stream max duration and start offset

**Comment by bastimeyer** [comment]
Closed by accident (because of how my sentence was structured in #5504 and how GH parses these commands :man_facepalming:)

**Comment by bastimeyer** [comment]
Going to merge #5526 after the next release...

I have the other refactoring changes ready, but those require at least two more PRs and are (obviously) based on #5526. I don't want the changes of #5526 included in the next release because of the **internal** "breaking" changes (method name changes, etc). The follow-up PRs will also include "breaking" changes with the move towards stream sub-packages for `segmented`, `dash` and `hls`, and it would make sense to have them combined in one release. I'm putting breaking changes into quotes again, because this will only affect the HLS and DASH parser modules, which are not meant as public interfaces. The Twitch plugin is an exception, but it's a mainline (non-3rd-party) plugin, so this doesn't matter.

I've talked about the sub-packages already, but now with the base `Segment` class needed for implementing a common stream-duration / stream-start-offset implementation for segmented streams, this is now a valid reason to do that, so that the HLS M3U8 parser and DASH manifest parser don't have to add a dependency on the same module where the segmented stream classes are defined, and the base `Segment` can be defined separately. Sub-packages also allow exporting stuff explicitly.

The layout will then look like this:

```
stream
  dash
    __init__.py  (`stream.dash` imports remain the same via re-exports)
    dash.py
    manifest.py  (parser + `DASHSegment` (could also be moved to dedicated module))
  hls
    __init__.py  (`stream.hls` imports remain the same via re-exports)
    hls.py
    m3u8.py  (parser + `HLSSegment`/`HLSPlaylist` (could also be moved to dedicated module))
  segmented
    __init__.py
    concurrent.py  (compat module)
    segment.py  (`Segment` base class)
    segmented
```

The modules of those sub-packages could explicitly be declared private, but that would require overriding the logger name, and I don't think it's worth.

```
GIT_PAGER=cat git log --graph --format=oneline --abbrev-commit master..stream/base-segment

* 011fdfca (HEAD -> stream/base-segment) stream.segmented: add common base Segment class
* 24f2c248 plugins.ustreamtv: refactor using dataclasses
* 9512d1e3 stream.dash: make DASHStream.duration non-optional
* 46b0b130 stream.dash: rename DASHSegment.number to num
* ed345175 stream.dash: rename DASHSegment.url attr to uri
* fbde06be stream.dash: rename Segment to DASHSegment
* 26141a00 stream.hls: rename Segment to HLSSegment
* 464a5bee (stream/subpackages) stream.segmented: move CompatThreadPoolExecutor
* d01d0c9f stream: switch to stream.hls sub-package
* f06753f1 stream: switch to stream.dash sub-package
* 8eb448a6 stream: switch to stream.segmented sub-package
* 4bb8cc14 (github/stream/hls/refactor-segment, stream/hls/refactor-segment) stream.hls: refactor M3U8 playlist loading
* 60b1aee7 stream.hls: update methods and attributes
* a3f8cb85 stream.hls: remove Sequence named tuple wrapper
* 8b1da42f stream.hls: turn Segment/Playlist into dataclasses
```

**Comment by gravyboat** [comment]
The layout structure makes sense to me and I agree regarding not overriding the logger name.
