### ISSUE TITLE
Where  does one go to share a GUI/frontend?

### ISSUE THREAD

**Issue by techmouse** [streamlink/streamlink#778]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I looked around but I couldn't find any place where they can be submitted. Can someone help me out?

**Comment by bastimeyer** [comment]
There's currently no official list of third party tools like GUIs/frontends, etc.
AFAIK, the Livestreamer repository had its wiki with a dedicated page for this that could be edited by everyone. I personally would welcome a menu on the website for this though, so that there can be a bit of quality assurance without fear of vandalism. Yes, I know, the wiki is just a git repo and changes can be undone, but this stuff gets usually noticed late.

Do you want to submit your own project or is it from somebody else? Could you please provide some infos?

**Comment by techmouse** [comment]
Well it's just a lightweight bash script I've been adding to and expanding on for the last couple of years. I've added support for sites streamlink and livestreamer don't support, along with a history of saved links, the ability to open chats for a couple of sites, and a few other features I've added for use for my family and myself around the home. I honestly don't know how it compares to other frontends, and I usually don't share my projects with the public, but I guess I've been feeling brave enough (or dumb enough) to open myself up to criticism for some reason.

**Comment by beardypig** [comment]
@techmouse, we're always interested in adding extra plugins ... maybe we can port some over in to `streamlink` :)

**Comment by techmouse** [comment]
Haha well try not to get too excited. Like I said it's all done in bash so I doubt it would be useful to anything other than Linux systems and maybe Macs.

**Comment by dehesselle** [comment]
I'm leaving my 2 cents in here (instead of just silently subscribing) since I'd be interested in this as well. Anything that could lead to more exposure for Streamlink is a good thing, the work you guys are doing __does matter__ to a lot of people. And seeing what others are doing and being a part of that would make me feel like giving something back. Also a good thing :wink:.

**Comment by techmouse** [comment]
Well I don't know where to put this so I guess I'll just leave it here. Below is the link to the script and the description. If this is a problem, let me know.

https://www.dropbox.com/s/048p1u5wheo1r9d/livestreamlinkgui-public

This is LiveStreamLinkGUI. It's a lightweight GUI for Livestreamer, Streamlink, and any future forks. I made it for the personal use of my family and myself, but when I looked around, I saw people making requests for things I've already implemented. So I decided to share it. Its only requirements are BASH, rtmpdump, and zenity. I wrote it in Linux, for Linux, but because it's a BASH script, it should (in theory) work for any platform that supports BASH and its requirements. I hear Win10 has some kind of BASH support but I have no idea how capable it is of running this or any other script.


Features:
Open Chats.
Some websites have popout chats, such as twitch and vaughnlive. When you give LiveStreamLinkGUI a link for one of these sites, it can ask if you want to open the chat for that stream in your browser. It's important to know only the chat will be opened. So you don't have to worry about your browser eating up a lot of your system resources just to take part in the chat. I designed LiveStreamLinkGUI in a way where adding support for other sites shouldn't be difficult at all. All you need to know is the popout chat's URL and how to parse it.

Save Links.
LiveStreamLinkGUI can also save links. This makes it easy to keep track of your favorite streams and even open them without running your browser.

Loop Forever.
If the stream is lost or closed for whatever reason, you have the option to "loop forever". While doing so, LiveStreamLinkGUI will keep trying to reopen the stream until the script is manually killed. This is best used in a media setup, so you can keep watching your streams while you fall asleep, work, clean the house, or whatever. It works very well with the shutdown command. An example of the shutdown command (which can differ from distro to distro) is sudo shutdown -hP <minutes>, which will shutdown the system after the specified number of minutes. So it's similar to sleepmode for TVs.

I've added support for sites like arconaitv.me, funhaus.roosterteeth.com, and a few other sites. LiveStreamLinkGUI is designed so that adding support for other sites shouldn't be much of a chore.


Configurations:
All of the user specific configurations are at the top of the script. I would recommend going through them before running the script, but there is also a first time setup GUI which will help take you through the more basic configurations.


How to use:
If you want to open a new stream, all you have to do is execute the script and select "Open A New Link". A text input box will appear and you can drag and drop the link to that text box and click "OK". You can also copy-paste the link or manually type it in, if you so choose.

When the player closes, you're presented with a list of options. You can reopen it (if the stream is online), save the link for future use, loop it forever, open a new stream, open a saved stream, etc, etc. To save you a click, selecting "Close Program", is the same as clicking "Cancel", pressing ESC, or closing the window in any other way. So you don't have to scroll to the bottom every time you're done with the script.

For ease of use, I have a launcher for LiveStreamLinkGUI in my DE's panel. For media machines, I also keep a launcher for timed shutdowns. It makes it very easy to watch streams while falling asleep using only a pointer device. I'm not telling you what to do, I'm just telling you what I do.


As a side note, there's a VLC script that allows VLC to play Youtube playlists. Naturally, LiveStreamLinkGUI gets along very well with this.


Feel free to make whatever changes you want with this. If you make a change, such as adding chat support for other sites, or site support for any sites livestreamer/streamlink don't support, please let me know so I can add the changes too. If you redistribute this script, I would like to ask that you please give me credit as "Mouse". Thank you and enjoy!

**Comment by dehesselle** [comment]
@techmouse You've put a lot of effort in your comment above, may I ask why you didn't just setup a Git repository of your own, put everything there and link that back here? That would be the best way not only to preserve your work but to enable/encourage future additions as you already mentioned.

**Comment by techmouse** [comment]
@dehesselle Well at the risk of sounding foolish, I appear to be very github illiterate. While looking through different projects, I've had a heck of a time just trying to find the pages other people were talking about. I eventually went to google and did a search for "keywords site:github.com". I don't think I'm getting old, but just trying to view the content on here sure makes me feel that way. So needless to say, learning how to set up a github project seems like a chore unto itself. I wouldn't even know where to begin for this one situation alone.

**Comment by dehesselle** [comment]
@techmouse Not foolish - everybody has to start somewhere. I created a repository and requested a transfer to you. Now the only thing you have to do is accept the transfer.

**Comment by techmouse** [comment]
@dehesselle Thank you very much! Clicking the link that was emailed to me took me to github's tutorial on how to use github. Ask and you shall receive. If only I had known about it sooner.

**Comment by cirrusUK** [comment]
i Like this, maybe could implement url's from this simple shell script giving user choices.
     https://github.com/streamlink/streamlink/issues/872 
 a database of all/popular streams added to the frontend would be nice for the non DOS/bash types ;) 
 the filmon/vaughnlive url's are static, not too sure about others.

**Comment by techmouse** [comment]
@cirrusUK 

All filmon links I checked were region locked so I couldn't verify much. But it appears streamlink supports it so LiveStreamLinkGUI would have no problem with it either. And of course you can save the links for future use.

I checked all over LondonLive and I couldn't find where you got that m3u8 link from. I don't know if it's because LondonLive is region locked too or if I'm on the wrong site all together but I would need more information to support it.

Concerning the Twit link, is that the same Twit as Twit.tv? As in Leo Laporte's Twit? If so, they have a Twitch account: twitch.tv/twit, which means livestreamer/streamlink support it. I also added support for Twit.tv, including non-twitch.tv videos.

As for the rest of the links, I added a new experimental way to automatically search pages for supported video types. So any page that has a m3u8/mp4/webm/etc link will automatically be parsed and piped into the video player. This should make it much easier to watch unsupported sites and even add support for them yourself. So if something doesn't work with Livestreamer, Streamlink, or other forks, give this a shot.

https://github.com/techmouse/livestreamlinkgui

**Comment by beardypig** [comment]
If anyone is interested @karlo2105 and I have been working on this list of live TV channels: https://beardypig.github.io/tv-stream-db/

**Comment by cirrusUK** [comment]
@techmouse   
                            Yeah sorry, some of the links might well be dead, i wrote that script a while back , yes it is twit.tv.

@beardypig 
                          Thanks for the list.
