### ISSUE TITLE
Review env variables for Travis compromise 

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#899]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Earlier today Travis.ci reported an issue related to env variable vulnerabilities (https://blog.travis-ci.com/2017-05-08-security-advisory). We should make sure any variables that could have potentially been leaked are updated. 

I believe this impacts the following aspects:

- @sbstp and the variables associated there for doc pushes (not 100% sure here, please review the  Travis keys)
- The bintray build system
- The release API key

**Comment by sbstp** [comment]
From what I understand, some information could have been leaked if travis failed to push to the docs repo. They edited the archived logs to remove this information, and have fixed the new logs. Now if someone got that information they would have to push to the docs repo. They could change the download links. However, we don't put any binaries on that website, we use the Github releases page. I doubt that someone has this information, but better safe than sorry. I'll look into resetting the keys, but I don't think my access rights allow me to view the tokens anymore.

**Comment by sbstp** [comment]
This is the guide that I've used before. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials. These are the steps to get a new set of keys:

1. Generate a new ssh key pair with no passphrase.
2. Install the `travis` program (it's a ruby gem)
3. Encrypt the private key with the `travis` program
4. Modify the call to the `openssl` command to use the new env variables in `script/pushdocs.sh` 
5. Add the public key to the `streamlink.github.io` repo, remove the old one.
6. Replace `deploy-key.enc` with the new encrypted private key file
7. Push the changes to the `streamlink` repo.
8. Delete the ssh key pair from your computer.

**Comment by back-to** [comment]
because of https://github.com/streamlink/streamlink/pull/1802

the **old key** can be removed from

https://github.com/streamlink/streamlink.github.io/settings/keys

and this could be closed.

**Comment by beardypig** [comment]
I believe `encrypted_25fada573976_iv` and `encrypted_25fada573976_key` can be removed from the Travis settings too.

**Comment by beardypig** [comment]
All the variables have been updated since the breach.

**Comment by beardypig** [comment]
Related to this, I created a [streamlink-bot](https://github.com/streamlink-bot) account that is a member (not owner/admin) of the Streamlink organisation, but only has write access to the `streamlink` repo at the moment. I have updated the `RELEASES_API_KEY` one for the [streamlink-bot](https://github.com/streamlink-bot) user, so that releases will be made by [streamlink-bot](https://github.com/streamlink-bot), rather than me :)

And yes, the bot has the silly dog avatar ;)
